import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Home Page | lama-dev Tutorial",
    template: "%s | Next14",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-[100dvh] flex flex-col justify-between items-center`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
